cacheFolder: "./.yarn/cache"
cacheMigrationMode: "required-only"
compressionLevel: 0
enableGlobalCache: true
enableNetwork: true
enableOfflineMode: false
enableColors: true
networkConcurrency: 50
pnpUnpluggedFolder: "./.yarn/unplugged"
nodeLinker: "node-modules"
defaultSemverRangePrefix: "^"