name: Restrict Merges

on:
  pull_request:
    branches:
      - test
      - production

jobs:
  check-merge-restrictions:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge restrictions
        run: |
          if [[ "${{ github.base_ref }}" == "test" ]]; then
            echo "Merging into 'test' is only allowed from 'main'."
            if [[ "${{ github.head_ref }}" != "main" ]]; then
              echo "Error: Merges into 'test' are only allowed from the 'main' branch."
              exit 1
            else
              echo "Merge into 'test' is allowed from 'main'."
            fi
          elif [[ "${{ github.base_ref }}" == "production" ]]; then
            echo "Merging into 'production' is only allowed from 'test'."
            if [[ "${{ github.head_ref }}" != "test" ]]; then
              echo "Error: Merges into 'production' are only allowed from the 'test' branch."
              exit 1
            else
              echo "Merge into 'production' is allowed from 'test'."
            fi
          else
            echo "No merge restrictions for this branch."
          fi
